# Generated by Django 3.0.8 on 2020-10-12 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_posts_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
