# Generated by Django 3.0.8 on 2020-10-19 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0008_followers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Followers',
        ),
    ]
