name: Testing

on: push

jobs:
  test_project:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Django
        run: 
          pip install django
      - name: test
        run: python manage.py test
